// src/components/Footer/FooterComponent.tsx
import * as React from 'react'
import styled from 'styled-components'

const HeaderWrapper = styled.div`
    display: flex;
    flex-direction: row;
    align-items: center;
    border-top: 1px solid ${({ theme }: PropsTheme) => theme.colors.secondary};
    height: 30px;
    padding: 1em 2em;
`

const DesignedBy = styled.small`
    margin-left: auto;   
`

export const FooterComponent: React.FC = () => (
  <>
    <HeaderWrapper>
      <small>{new Date().getFullYear()}</small>
      <DesignedBy>Designed by CAGH</DesignedBy>
    </HeaderWrapper>
  </>
)

// src/components/layout/Footer.svelte
<footer>
  <span>{new Date().getFullYear()}</span>
  <span class="by-cagh">Designed by CAGH</span>
</footer>

<style>
  footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .by-cagh {
    padding: var(--padding-small);
    color: var(--secondary-color);
    border: 2px solid var(--secondary-color);
    border-radius: var(--border-radius-small);
  }
</style>
