// src/components/Header/HeaderComponent.tsx
import * as React from 'react'
import styled from 'styled-components'

const Brand = styled.h2`
    margin-block-end: 0;
`

const HeaderWrapper = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  color: white;
  background: ${
  ({ theme }: PropsTheme) => theme.colors.secondary
};
  padding: 1em 2em;
`

export const HeaderComponent: React.FC = () => (
  <>
    <HeaderWrapper>
      <Brand>
        CAGH
      </Brand>
    </HeaderWrapper>
  </>
)

// src/components/layout/Header.svelte
<script>
  export let theme;
  export let prefersDarkScheme;

  export let handleClick;
</script>

<header>
  <h2 id="my-site-brand">CAGH</h2>
  <div id="color-switch" on:click={handleClick}>🌓</div>
</header>

<style>
  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  #color-switch {
    cursor: pointer;
    font-size: 2rem;
    user-select: none;
  }

  #my-site-brand {
    background-color: var(--secondary-color);
    padding: var(--padding-small);
    border-radius: var(--border-radius-small);
    color: var(--primary-color);
  }
</style>
